// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Toe.SPIRV.CodeGenerator.Views
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Toe.SPIRV.CodeGenerator.Model.Grammar;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class InstructionTemplate : InstructionTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.Collections.Generic;\r\nusing Toe.SPIRV.Spv;\r\n\r\n");
            
            #line 10 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

    var isType = _instruction.IdResult!=null && _instruction.Name.StartsWith("OpType");

            
            #line default
            #line hidden
            this.Write("\r\nnamespace Toe.SPIRV.Instructions\r\n{\r\n    public partial class ");
            
            #line 16 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_instruction.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 16 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isType ? "TypeInstruction" : (_instruction.IdResult!=null ? "InstructionWithId" : "Instruction")));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 18 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_instruction.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n        }\r\n\r\n        public override Op OpCode { get { return Op.");
            
            #line 22 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_instruction.Name));
            
            #line default
            #line hidden
            this.Write("; } }\r\n\r\n");
            
            #line 24 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

    foreach(var op in _instruction.AllOperands().Where(_=>_.Kind != SpirvOperandKind.IdResult))
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 28 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewUtils.GetOperandType(op)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 28 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\r\n");
            
            #line 30 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        public override IEnumerable<ReferenceProperty> GetReferences()\r\n        {" +
                    "\r\n");
            
            #line 35 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

    foreach(var op in _instruction.AllOperands().Where(_=>_.Kind == SpirvOperandKind.IdRef))
    {
        if (op.Quantifier == SpirvOperandQuantifier.Repeated)
        {

            
            #line default
            #line hidden
            this.Write("            for (int i=0; i<");
            
            #line 41 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(".Count; ++i)\r\n                yield return new ReferenceProperty(\"");
            
            #line 42 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("\"+i, ");
            
            #line 42 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("[i]);\r\n");
            
            #line 43 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("            yield return new ReferenceProperty(\"");
            
            #line 48 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 48 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 49 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("            yield break;\r\n        }\r\n\r\n        public override void Parse(WordRea" +
                    "der reader, uint wordCount)\r\n        {\r\n            var end = reader.Position+wo" +
                    "rdCount-1;\r\n");
            
            #line 59 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

    foreach(var op in _instruction.AllOperands())
    {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 63 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 63 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewUtils.GetOperandParser(op)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 64 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        if (op.Kind == SpirvOperandKind.IdResult)
        {

            
            #line default
            #line hidden
            this.Write("            reader.Instructions.Add(this);\r\n");
            
            #line 69 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public override uint GetWordCount()\r\n        {\r\n            " +
                    "uint wordCount = 0;\r\n");
            
            #line 78 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

    foreach(var op in _instruction.AllOperands())
    {
        if (op.Quantifier == SpirvOperandQuantifier.Optional && op.Kind != SpirvOperandKind.IdRef)
        {

            
            #line default
            #line hidden
            this.Write("            wordCount += ");
            
            #line 84 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("?.GetWordCount() ?? 0u;\r\n");
            
            #line 85 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("            wordCount += ");
            
            #line 90 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(".GetWordCount();\r\n");
            
            #line 91 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("            return wordCount;\r\n        }\r\n\r\n        public override void Write(Wo" +
                    "rdWriter writer)\r\n        {\r\n");
            
            #line 100 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

    foreach(var op in _instruction.AllOperands())
    {
        if (op.Quantifier == SpirvOperandQuantifier.Optional)
        {

            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 106 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" != null) ");
            
            #line 106 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(".Write(writer);\r\n");
            
            #line 107 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 112 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(".Write(writer);\r\n");
            
            #line 113 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public override string ToString()\r\n        {\r\n");
            
            #line 121 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\InstructionTemplate.tt"

if (_instruction.IdResultType != null && _instruction.IdResult != null)
{
    WriteLine("            return $\"{IdResultType} {IdResult} = {OpCode} "+string.Join(" ", _instruction.Operands.Select(_=>"{"+_.Name+"}"))+"\";");
}
else if (_instruction.IdResult != null)
{
    WriteLine("            return $\"{IdResult} = {OpCode} "+string.Join(" ", _instruction.Operands.Select(_=>"{"+_.Name+"}"))+"\";");
}
else
{
    WriteLine("            return $\"{OpCode} "+string.Join(" ", _instruction.Operands.Select(_=>"{"+_.Name+"}"))+"\";");
}

            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class InstructionTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
