// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Toe.SPIRV.CodeGenerator.Views
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Toe.SPIRV.CodeGenerator.Model.Grammar;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class NodeTemplate : NodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Toe.S" +
                    "PIRV.Instructions;\r\nusing Toe.SPIRV.Reflection.Types;\r\nusing Toe.SPIRV.Spv;\r\n\r\nn" +
                    "amespace Toe.SPIRV.Reflection.Nodes\r\n{\r\n    public partial class ");
            
            #line 16 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 16 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseClass));
            
            #line default
            #line hidden
            
            #line 16 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_instruction.HasDefaultExit?", INodeWithNext":""));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 18 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n        }\r\n");
            
            #line 21 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

{

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 25 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 25 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", _operands.Concat(new KeyValuePair<string, string>("debugName","string")).Select(_=>$"{_.Value} {ViewUtils.ToVarName(_.Key)}"))));
            
            #line default
            #line hidden
            this.Write(" = null)\r\n        {\r\n");
            
            #line 27 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

foreach (var op in _operands)
{
    if (op.Value.StartsWith("IList<") || op.Value.StartsWith("IEnumerable<"))
    {

            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 33 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewUtils.ToVarName(op.Key)));
            
            #line default
            #line hidden
            this.Write(" != null) { foreach (var node in ");
            
            #line 33 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewUtils.ToVarName(op.Key)));
            
            #line default
            #line hidden
            this.Write(") this.");
            
            #line 33 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Key));
            
            #line default
            #line hidden
            this.Write(".Add(node); }\r\n");
            
            #line 34 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 39 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Key));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 39 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewUtils.ToVarName(op.Key)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 40 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("            DebugName = debugName;\r\n        }\r\n");
            
            #line 46 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n        public override Op OpCode => Op.");
            
            #line 50 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_instruction.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 51 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
if (_instruction.HasDefaultExit)
{

            
            #line default
            #line hidden
            this.Write(@"
        /// <summary>
        /// Next operation in sequence
        /// </summary>
        public ExecutableNode Next { get; set; }

        public override ExecutableNode GetNext()
        {
            return Next;
        }

        public T Then<T>(T node) where T: ExecutableNode
        {
            Next = node;
            return node;
        }
");
            
            #line 71 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}
foreach (var op in _instruction.Operands)
{
    switch (op.Class)
    {
        case SpirvOperandClassification.Type:

            
            #line default
            #line hidden
            this.Write("\r\n        public SpirvTypeBase ");
            
            #line 80 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 81 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
            break;
        case SpirvOperandClassification.Exit:
        case SpirvOperandClassification.Input:

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 87 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetNodeType(op)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 87 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 88 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
            break;
        case SpirvOperandClassification.RepeatedInput:

            
            #line default
            #line hidden
            this.Write("\r\n        public IList<");
            
            #line 93 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetNodeType(op)));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 93 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; } = new PrintableList<");
            
            #line 93 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetNodeType(op)));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 94 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
            break;
        default:
            if (op.Quantifier == SpirvOperandQuantifier.Repeated)
            {

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 101 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyType(op)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 101 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; } = new ");
            
            #line 101 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyType(op).Replace("IList<","List<")));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 102 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 108 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyType(op)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 108 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 109 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

            }
            break;
    }
}

if (_instruction.IdResultType != null)
{

            
            #line default
            #line hidden
            this.Write("\r\n        public SpirvTypeBase ResultType { get; set; }\r\n\r\n        public overrid" +
                    "e SpirvTypeBase GetResultType()\r\n        {\r\n            return ResultType;\r\n    " +
                    "    }\r\n");
            
            #line 125 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}

if (_instruction.Operands.Any(op=>op.Class == SpirvOperandClassification.Input || op.Class == SpirvOperandClassification.RepeatedInput))
{

            
            #line default
            #line hidden
            this.Write("\r\n        public override IEnumerable<NodePinWithConnection> InputPins\r\n        {" +
                    "\r\n            get\r\n            {\r\n");
            
            #line 136 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
foreach (var op in _instruction.Operands)
{
    if (op.Class == SpirvOperandClassification.Input)
    {

            
            #line default
            #line hidden
            this.Write("                yield return CreateInputPin(nameof(");
            
            #line 142 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("), ");
            
            #line 142 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 143 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
    }
    else if (op.Class == SpirvOperandClassification.RepeatedInput)
    {

            
            #line default
            #line hidden
            this.Write("                for (var index = 0; index < ");
            
            #line 148 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(".Count; index++)\r\n                {\r\n                    yield return CreateInput" +
                    "Pin(nameof(");
            
            #line 150 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(") + index, ");
            
            #line 150 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("[index]);\r\n                }\r\n");
            
            #line 152 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
    }
}

            
            #line default
            #line hidden
            this.Write("                yield break;\r\n            }\r\n        }\r\n");
            
            #line 159 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}

            
            #line default
            #line hidden
            this.Write("\r\n        public override IEnumerable<NodePin> OutputPins\r\n        {\r\n           " +
                    " get\r\n            {\r\n");
            
            #line 167 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
if (_instruction.IdResultType != null)
{

            
            #line default
            #line hidden
            this.Write("                yield return new NodePin(this, \"\", ResultType);\r\n");
            
            #line 172 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}

            
            #line default
            #line hidden
            this.Write("                yield break;\r\n            }\r\n        }\r\n\r\n");
            
            #line 179 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
if (_instruction.HasDefaultEnter)
{

            
            #line default
            #line hidden
            this.Write("        public override IEnumerable<NodePin> EnterPins\r\n        {\r\n            ge" +
                    "t\r\n            {\r\n                yield return new NodePin(this, \"\", null);\r\n   " +
                    "         }\r\n        }\r\n");
            
            #line 190 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}

            
            #line default
            #line hidden
            this.Write("\r\n        public override IEnumerable<NodePinWithConnection> ExitPins\r\n        {\r" +
                    "\n            get\r\n            {\r\n");
            
            #line 198 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
if (_instruction.HasDefaultExit)
{

            
            #line default
            #line hidden
            this.Write("                yield return CreateExitPin(\"\", GetNext());\r\n");
            
            #line 203 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}
foreach (var op in _instruction.Operands)
{
    if (op.Class == SpirvOperandClassification.Exit)
    {

            
            #line default
            #line hidden
            this.Write("                yield return CreateExitPin(nameof(");
            
            #line 210 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("), ");
            
            #line 210 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 211 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
    }
}

            
            #line default
            #line hidden
            this.Write("                yield break;\r\n            }\r\n        }\r\n\r\n        public ");
            
            #line 219 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(@" WithDecoration(Spv.Decoration decoration)
        {
            AddDecoration(decoration);
            return this;
        }

        public override void SetUp(Instruction op, SpirvInstructionTreeBuilder treeBuilder)
        {
            base.SetUp(op, treeBuilder);
            SetUp((");
            
            #line 228 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(opname));
            
            #line default
            #line hidden
            this.Write(")op, treeBuilder);\r\n        }\r\n\r\n        public ");
            
            #line 231 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" SetUp(Action<");
            
            #line 231 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("> setup)\r\n        {\r\n            setup(this);\r\n            return this;\r\n        " +
                    "}\r\n\r\n        private void SetUp(");
            
            #line 237 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(opname));
            
            #line default
            #line hidden
            this.Write(" op, SpirvInstructionTreeBuilder treeBuilder)\r\n        {\r\n");
            
            #line 239 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
if (_instruction.IdResultType != null)
{

            
            #line default
            #line hidden
            this.Write("            ResultType = treeBuilder.ResolveType(op.IdResultType);\r\n");
            
            #line 244 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}

foreach (var op in _instruction.Operands)
{
    switch (op.Class)
    {
        case SpirvOperandClassification.Type:

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 253 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" = treeBuilder.ResolveType(op.");
            
            #line 253 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 254 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
            break;
        case SpirvOperandClassification.Exit:
        case SpirvOperandClassification.Input:

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 259 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 259 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CastNodeType(op)));
            
            #line default
            #line hidden
            this.Write("treeBuilder.GetNode(op.");
            
            #line 259 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 260 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
            break;
        case SpirvOperandClassification.RepeatedInput:

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 264 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" = treeBuilder.GetNodes(op.");
            
            #line 264 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 265 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
            break;
        default:
            if (op.Quantifier == SpirvOperandQuantifier.Repeated)
            {

            
            #line default
            #line hidden
            this.Write("            foreach (var item in op.");
            
            #line 271 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(") { ");
            
            #line 271 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(".Add(treeBuilder.Parse(item)); }\r\n");
            
            #line 272 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 277 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" = op.");
            
            #line 277 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 278 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

            }
            break;
    }
}

            
            #line default
            #line hidden
            this.Write("            SetUpDecorations(op, treeBuilder);\r\n        }\r\n\r\n        /// <summary" +
                    ">Returns a string that represents the ");
            
            #line 287 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" object.</summary>\r\n        /// <returns>A string that represents the ");
            
            #line 288 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" object.</returns>\r\n        /// <filterpriority>2</filterpriority>\r\n        publi" +
                    "c override string ToString()\r\n        {\r\n            return $\"");
            
            #line 292 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 292 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", _operands.Concat(new KeyValuePair<string, string>("DebugName","string")).Select(_=>$"{{{_.Key}}}"))));
            
            #line default
            #line hidden
            this.Write(")\";\r\n        }\r\n    }\r\n");
            
            #line 295 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
if (_instruction.HasDefaultEnter)
{

            
            #line default
            #line hidden
            this.Write("\r\n    public static partial class INodeWithNextExtensionMethods\r\n    {\r\n        p" +
                    "ublic static ");
            
            #line 302 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" Then");
            
            #line 302 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(this INodeWithNext node");
            
            #line 302 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

foreach (var op in _instruction.Operands)
{
    this.Write(", ");
    switch (op.Class)
    {
        case SpirvOperandClassification.Type:
            this.Write($"SpirvTypeBase {ViewUtils.ToVarName(op.Name)}");
            break;
        case SpirvOperandClassification.Exit:
        case SpirvOperandClassification.Input:
            this.Write($"{GetNodeType(op)} {ViewUtils.ToVarName(op.Name)}");
            break;
        case SpirvOperandClassification.RepeatedInput:
            this.Write($"IEnumerable<{GetNodeType(op)}> {ViewUtils.ToVarName(op.Name)}");
            break;
        default:
            this.Write($"{GetPropertyType(op)} {ViewUtils.ToVarName(op.Name)}");
            break;
    }
}

            
            #line default
            #line hidden
            this.Write(", string debugName = null)\r\n        {\r\n            return node.Then(new ");
            
            #line 325 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 325 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"

{
    var sep = "";
    foreach (var op in _instruction.Operands)
    {
        this.Write(sep); sep = ", ";
        this.Write(ViewUtils.ToVarName(op.Name));
    }
    this.Write($"{sep}debugName");
}

            
            #line default
            #line hidden
            this.Write("));\r\n        }\r\n    }\r\n");
            
            #line 338 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeTemplate.tt"
 
}

            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class NodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
