// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Toe.SPIRV.CodeGenerator.Views
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Toe.SPIRV.CodeGenerator.Model.Grammar;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class NodeVisitor : NodeVisitorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.Collections.Generic;\r\nusing Toe.SPIRV.Reflection.Nodes;\r\nusing Toe.S" +
                    "PIRV.Reflection.Types;\r\n\r\nnamespace Toe.SPIRV.Reflection\r\n{\r\n    public abstract" +
                    " class NodeVisitor\r\n    {\r\n        Queue<Node> _nodesToVisit = new Queue<Node>()" +
                    ";\r\n        HashSet<Node> _visitedNodes = new HashSet<Node>();\r\n\r\n        public " +
                    "virtual void Visit(Node node)\r\n        {\r\n            ScheduleVisit(node);\r\n    " +
                    "        while (_nodesToVisit.Count > 0)\r\n            {\r\n                VisitNod" +
                    "e(_nodesToVisit.Dequeue());\r\n            }\r\n        }\r\n\r\n        protected virtu" +
                    "al void ScheduleVisit(Node node)\r\n        {\r\n            if (node != null && _vi" +
                    "sitedNodes.Add(node))\r\n                _nodesToVisit.Enqueue(node);\r\n        }\r\n" +
                    "\r\n        protected virtual void ScheduleVisit(IEnumerable<Node> nodes)\r\n       " +
                    " {\r\n            foreach (var node in nodes)\r\n            {\r\n                Sche" +
                    "duleVisit(node);\r\n            }\r\n        }\r\n\r\n        protected virtual void Sch" +
                    "eduleVisit(IEnumerable<PairNodeNode> nodes)\r\n        {\r\n            foreach (var" +
                    " node in nodes)\r\n            {\r\n                ScheduleVisit(node.Node);\r\n     " +
                    "           ScheduleVisit(node.Node2);\r\n            }\r\n        }\r\n\r\n        prote" +
                    "cted virtual void ScheduleVisit(IEnumerable<PairLiteralIntegerNode> nodes)\r\n    " +
                    "    {\r\n            foreach (var node in nodes)\r\n            {\r\n                S" +
                    "cheduleVisit(node.Node);\r\n            }\r\n        }\r\n\r\n        protected virtual " +
                    "void ScheduleVisit(IEnumerable<PairNodeLiteralInteger> nodes)\r\n        {\r\n      " +
                    "      foreach (var node in nodes)\r\n            {\r\n                ScheduleVisit(" +
                    "node.Node);\r\n            }\r\n        }\r\n\r\n        protected virtual void VisitTyp" +
                    "e(SpirvTypeBase node)\r\n        {\r\n        }\r\n\r\n        private void VisitNode(No" +
                    "de node)\r\n        {\r\n            switch (node.OpCode)\r\n            {\r\n");
            
            #line 74 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"

foreach (var instruction in _grammar.Instructions.Values)
{

            
            #line default
            #line hidden
            this.Write("                case Spv.Op.");
            
            #line 78 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name));
            
            #line default
            #line hidden
            this.Write(": Visit");
            
            #line 78 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write("((");
            
            #line 78 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(")node); return;\r\n");
            
            #line 79 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"

}

            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n");
            
            #line 84 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"

foreach (var instruction in _grammar.Instructions.Values)
{

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual void Visit");
            
            #line 89 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 89 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(" node)\r\n        {\r\n");
            
            #line 91 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"

if (instruction.Name.StartsWith("OpType"))
{

            
            #line default
            #line hidden
            this.Write("            VisitType(node);\r\n");
            
            #line 96 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"

}
foreach (var operand in instruction.Operands)
{
    switch (operand.Kind)
    {
        case SpirvOperandKind.IdRef:
        case SpirvOperandKind.PairLiteralIntegerIdRef:
        case SpirvOperandKind.PairIdRefIdRef:
        case SpirvOperandKind.PairIdRefLiteralInteger:
        {

            
            #line default
            #line hidden
            this.Write("            ScheduleVisit(node.");
            
            #line 108 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operand.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 109 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"

            break;
        }
    }
}

            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 116 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\NodeVisitor.tt"

}

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class NodeVisitorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
