// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Toe.SPIRV.CodeGenerator.Views
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Toe.SPIRV.CodeGenerator.Model.Grammar;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ShaderToScriptConverterTemplate : ShaderToScriptConverterTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Collections.Generic;
using System.Globalization;
using Toe.Scripting;
using Toe.SPIRV.Reflection;
using Toe.SPIRV.Reflection.Types;
using Toe.SPIRV.Spv;
using Nodes=Toe.SPIRV.Reflection.Nodes;

namespace Toe.SPIRV
{
    internal class ShaderToScriptConverterBase
    {
        protected Script _script;
        protected Dictionary<Node, ScriptNode> _nodeMap = new Dictionary<Node, ScriptNode>();
        public ShaderToScriptConverterBase()
        {
            _script = new Script();
        }

        protected virtual ScriptNode VisitNode(Node node)
        {
            if (_nodeMap.TryGetValue(node, out var scriptNode))
            {
                return scriptNode;
            }

            switch (node.OpCode)
            {
");
            
            #line 36 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

foreach (var instruction in _grammar.Instructions.Values)
{
    if (!instruction.Name.StartsWith("OpType"))
    {

            
            #line default
            #line hidden
            this.Write("                case Op.");
            
            #line 42 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name));
            
            #line default
            #line hidden
            this.Write(": return Visit");
            
            #line 42 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write("((Nodes.");
            
            #line 42 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(") node);\r\n");
            
            #line 43 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n            throw new NotImplementedException(node.OpCode+\" is n" +
                    "ot implemented yet.\");\r\n        }\r\n\r\n");
            
            #line 52 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

foreach (var instruction in _grammar.Instructions.Values)
{
    if (!instruction.Name.StartsWith("OpType"))
    {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual ScriptNode Visit");
            
            #line 59 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write("(Nodes.");
            
            #line 59 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(" node)\r\n        {\r\n            var scriptNode = CreateNode(node, node.DebugName ?" +
                    "? \"");
            
            #line 61 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 61 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 61 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.HasDefaultEnter?"true":"false"));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 61 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((instruction.IdResultType!=null)?"GetTypeName(node.ResultType)":"null"));
            
            #line default
            #line hidden
            this.Write(", NodeCategory.");
            
            #line 61 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetNodeCategory(instruction)));
            
            #line default
            #line hidden
            this.Write(", null);\r\n");
            
            #line 62 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        if (instruction.HasDefaultExit)
        {

            
            #line default
            #line hidden
            this.Write("            scriptNode.ExitPins.Add(new PinWithConnection(\"\",null,GetExitConnecti" +
                    "on(node.Next)));\r\n");
            
            #line 67 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 70 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
 
foreach (var op in instruction.Operands)
{
    if (op.Class == SpirvOperandClassification.Exit)
    {

            
            #line default
            #line hidden
            this.Write("            scriptNode.ExitPins.Add(new PinWithConnection(nameof(node.");
            
            #line 76 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("),null, GetExitConnection(node.");
            
            #line 76 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(")));\r\n");
            
            #line 77 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
 
    }
    else if (op.Class == SpirvOperandClassification.Input)
    {

            
            #line default
            #line hidden
            this.Write("            scriptNode.InputPins.Add(new PinWithConnection(nameof(node.");
            
            #line 82 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("), GetTypeName(node.");
            
            #line 82 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("?.GetResultType()), GetOutputConnection(node.");
            
            #line 82 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(")));\r\n");
            
            #line 83 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
 
    }
    else if (op.Class == SpirvOperandClassification.RepeatedInput)
    {

            
            #line default
            #line hidden
            this.Write("            if (node.");
            
            #line 88 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n            {\r\n                for (var index = 0; index < node.");
            
            #line 90 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write(".Count; index++)\r\n                {\r\n                    var item = node.");
            
            #line 92 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("[index];\r\n                    scriptNode.InputPins.Add(new PinWithConnection(stri" +
                    "ng.Format(CultureInfo.InvariantCulture, \"");
            
            #line 93 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(op.Name));
            
            #line default
            #line hidden
            this.Write("{0}\", index), GetTypeName(item?.GetResultType()), GetOutputConnection(item)));\r\n " +
                    "               }\r\n            }\r\n");
            
            #line 96 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
 
    }
}

            
            #line default
            #line hidden
            this.Write("            return scriptNode;\r\n        }\r\n");
            
            #line 102 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("        protected string GetTypeName(SpirvTypeBase type)\r\n        {\r\n            " +
                    "if (type == null)\r\n                return null;\r\n            switch (type.OpCode" +
                    ")\r\n            {\r\n");
            
            #line 112 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

foreach (var instruction in _grammar.Instructions.Values)
{
    if (instruction.Name.StartsWith("OpType"))
    {

            
            #line default
            #line hidden
            this.Write("                case Op.");
            
            #line 118 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name));
            
            #line default
            #line hidden
            this.Write(": return Get");
            
            #line 118 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(6)));
            
            #line default
            #line hidden
            this.Write("Name((");
            
            #line 118 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(")type);\r\n");
            
            #line 119 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write(@"            }
            throw new NotImplementedException(type+"" is not implemented yet."");
        }

        protected virtual Connection GetExitConnection(Node node)
        {
            if (node == null)
                return null;
            return new Connection(VisitNode(node), """");
        }

        protected virtual Connection GetOutputConnection(Node node)
        {
            if (node == null)
                return null;
            return new Connection(VisitNode(node), """");
        }

");
            
            #line 141 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

foreach (var instruction in _grammar.Instructions.Values)
{
    if (instruction.Name.StartsWith("OpType"))
    {
        if (instruction.Name == "OpTypeVoid")
        {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual string GetVoidName(");
            
            #line 150 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(" type)\r\n        {\r\n            return \"void\";\r\n        }\r\n");
            
            #line 154 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypeBool")
        {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual string GetBoolName(");
            
            #line 160 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(" type)\r\n        {\r\n            return \"bool\";\r\n        }\r\n");
            
            #line 164 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypeInt")
        {

            
            #line default
            #line hidden
            this.Write(@"
        protected virtual string GetIntName(TypeInt type)
        {
            if (type.Signed)
            {
                switch (type.Width)
                {
                    case 8: return ""sbyte"";
                    case 16: return ""short"";
                    case 32: return ""int"";
                    case 64: return ""long"";
                }
            }
            else
            {
                switch (type.Width)
                {
                    case 8: return ""byte"";
                    case 16: return ""ushort"";
                    case 32: return ""uint"";
                    case 64: return ""ulong"";
                }
            }
            throw new NotImplementedException(type + "" is not implemented yet."");
        }
");
            
            #line 194 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypeFloat")
        {

            
            #line default
            #line hidden
            this.Write(@"
        protected virtual string GetFloatName(TypeFloat type)
        {
            switch (type.Width)
            {
                case 32: return ""float"";
                case 64: return ""double"";
            }
            throw new NotImplementedException(type+"" is not implemented yet."");
        }
");
            
            #line 209 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypeVector")
        {

            
            #line default
            #line hidden
            this.Write(@"
        protected virtual string GetVectorName(TypeVector type)
        {
            if (type.ComponentType == SpirvTypeBase.Float)
            {
                switch (type.ComponentCount)
                {
                    case 2: return ""vec2"";
                    case 3: return ""vec3"";
                    case 4: return ""vec4"";
                }
            }
            throw new NotImplementedException(type+"" is not implemented yet."");
        }
");
            
            #line 228 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypePointer")
        {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual string GetPointerName(TypePointer type)\r\n        {\r\n " +
                    "           return GetTypeName(type.Type)+\"*\";\r\n        }\r\n");
            
            #line 238 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypeStruct")
        {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual string GetStructName(TypeStruct type)\r\n        {\r\n   " +
                    "         return type.DebugName;\r\n        }\r\n");
            
            #line 248 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypeArray")
        {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual string GetArrayName(TypeArray type)\r\n        {\r\n     " +
                    "       return string.Format(CultureInfo.InvariantCulture, \"{0}[{1}]\", GetTypeNam" +
                    "e(type.ElementType), type.Length);\r\n        }\r\n");
            
            #line 258 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else if (instruction.Name == "OpTypeRuntimeArray")
        {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual string GetRuntimeArrayName(TypeRuntimeArray type)\r\n  " +
                    "      {\r\n            return string.Format(CultureInfo.InvariantCulture, \"{0}[*]\"" +
                    ", GetTypeName(type.ElementType));\r\n        }\r\n");
            
            #line 268 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual string Get");
            
            #line 274 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(6)));
            
            #line default
            #line hidden
            this.Write("Name(");
            
            #line 274 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instruction.Name.Substring(2)));
            
            #line default
            #line hidden
            this.Write(" type)\r\n        {\r\n            throw new NotImplementedException(type+\" is not im" +
                    "plemented yet.\");\r\n        }\r\n");
            
            #line 278 "C:\github\Toe.SPIRV\src\Toe.SPIRV.CodeGenerator\Views\ShaderToScriptConverterTemplate.tt"

        }
    }
}

            
            #line default
            #line hidden
            this.Write(@"
        protected ScriptNode CreateNode(Node node, string name, string type, bool hasDefaultEnter = false, string outputType = null, NodeCategory category = NodeCategory.Unknown, string value = null)
        {
            var scriptNode = new ScriptNode()
            {
                Name = name,
                Type = type,
                Category = category,
                Value = value
            };
            if (hasDefaultEnter)
            {
                scriptNode.EnterPins.Add(new Pin("""",null));
            }
            if (outputType != null)
            {
                scriptNode.OutputPins.Add(new Pin("""", outputType));
            }
            _script.Add(scriptNode);
            _nodeMap.Add(node, scriptNode);
            return scriptNode;
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ShaderToScriptConverterTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
